# Generated by Django 5.2.8 on 2025-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location2', models.CharField(default='Outlet_type', max_length=100)),
                ('surname', models.CharField(default='surname', max_length=100)),
                ('givenname', models.CharField(default='givenname', max_length=100)),
                ('nin', models.CharField(default='nin', max_length=14)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Outlet_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('location', models.CharField(default='location', max_length=100)),
                ('manager', models.CharField(default='manager', max_length=100)),
            ],
        ),
    ]
