# Generated by Django 5.2.8 on 2025-11-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='phonenumber',
            field=models.IntegerField(default=0, max_length='20'),
        ),
    ]
