# Generated by Django 5.2.8 on 2025-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0002_entry_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='gender',
            field=models.CharField(default='gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='phonenumber',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
