# Generated by Django 5.2.8 on 2025-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0003_entry_gender_alter_entry_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='stove',
            field=models.CharField(default='stove', max_length=20),
        ),
    ]
