# Generated by Django 5.2.8 on 2025-11-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0004_entry_stove'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='serialnumber',
            field=models.CharField(default='sb', max_length=20),
        ),
    ]
