# Generated by Django 5.2.8 on 2025-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0006_entry_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='subcidy',
            field=models.CharField(default='subcidy', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
