# Generated by Django 5.2.8 on 2025-11-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0007_entry_subcidy_alter_entry_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='others',
            field=models.CharField(default='others', max_length=10),
        ),
    ]
