# Generated by Django 5.2.8 on 2025-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0008_entry_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, default='2024-01-01'),
        ),
    ]
