# Generated by Django 5.2.8 on 2025-11-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0009_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='expected',
            field=models.IntegerField(default=0),
        ),
    ]
