# Generated by Django 5.2.8 on 2025-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0010_entry_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cashreceived',
            field=models.IntegerField(default=0),
        ),
    ]
