# Generated by Django 5.2.8 on 2025-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0012_entry_national'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='warranty',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
