# Generated by Django 5.2.8 on 2025-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0014_entry_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='national',
            field=models.FileField(blank=True, null=True, upload_to='national/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='recipt/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='warranty',
            field=models.FileField(blank=True, null=True, upload_to='warranty/'),
        ),
    ]
