# Generated by Django 5.2.8 on 2025-12-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0015_alter_entry_national_alter_entry_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='serialnumber', max_length=8)),
            ],
        ),
    ]
