# Generated by Django 5.2.8 on 2025-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0016_qr_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='serialnumber', max_length=8)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='qr_codes',
        ),
    ]
