# Generated by Django 5.2.8 on 2025-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0017_qrcodes_delete_qr_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodes',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='Doubleburner',
            field=models.CharField(default='double', max_length=8),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='Singleburner',
            field=models.CharField(default='single', max_length=8),
        ),
    ]
