# Generated by Django 5.2.8 on 2025-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0018_remove_qrcodes_serial_number_qrcodes_doubleburner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodes',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='qr_codeDB',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodesSB'),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='qr_codeSB',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodesDB'),
        ),
    ]
