# Generated by Django 5.2.8 on 2025-12-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0019_remove_qrcodes_qr_code_qrcodes_qr_codedb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='Doubleburner',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
