# Generated by Django 5.2.8 on 2025-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0020_alter_qrcodes_doubleburner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='qr_codeDB',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodesDB'),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='qr_codeSB',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodesSB'),
        ),
    ]
