# Generated by Django 5.2.8 on 2025-12-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0021_alter_qrcodes_qr_codedb_alter_qrcodes_qr_codesb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single1', models.CharField(blank=True, max_length=23, null=True)),
                ('double2', models.CharField(blank=True, max_length=23, null=True)),
            ],
        ),
    ]
