# Generated by Django 5.2.8 on 2025-12-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0022_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='Singleburner',
            field=models.CharField(blank=True, default='single', max_length=8, null=True),
        ),
    ]
