# Generated by Django 5.2.8 on 2025-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0023_alter_qrcodes_singleburner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcodes_double',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doubleburner', models.CharField(blank=True, max_length=8, null=True)),
                ('qr_codeDB', models.ImageField(blank=True, null=True, upload_to='qrcodesDB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='qrcodes',
            name='Doubleburner',
        ),
        migrations.RemoveField(
            model_name='qrcodes',
            name='qr_codeDB',
        ),
    ]
