# Generated by Django 5.2.8 on 2026-04-26 18:25

import GREENERGYFORMS.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0024_qrcodes_double_remove_qrcodes_doubleburner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpowerCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nin', models.CharField(max_length=14, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('referral_code', models.CharField(default=GREENERGYFORMS.models.generate_referral_code, max_length=20, unique=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpowerSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.CharField(max_length=100)),
                ('date_of_sale', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='GREENERGYFORMS.empowercustomer')),
                ('recommender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='GREENERGYFORMS.empowercustomer')),
            ],
        ),
        migrations.CreateModel(
            name='EmpowerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed')], default='PENDING', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_claimed', models.DateTimeField(blank=True, null=True)),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empower_claims', to='GREENERGYFORMS.empowercustomer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GREENERGYFORMS.empowersale')),
            ],
        ),
    ]
