# Generated by Django 5.2.8 on 2026-05-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0026_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empowercustomer',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
