# Generated by Django 5.2.8 on 2026-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0027_alter_empowercustomer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='empowercustomer',
            name='compliance_photo',
            field=models.ImageField(blank=True, null=True, upload_to='compliance_photos/'),
        ),
        migrations.AddField(
            model_name='empowercustomer',
            name='stove_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
