# Generated by Django 5.2.8 on 2026-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0028_empowercustomer_compliance_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empowercustomer',
            name='outlet',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
