# Generated by Django 5.2.8 on 2026-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREENERGYFORMS', '0029_empowercustomer_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='empowerclaim',
            name='sales_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
