# Generated by Django 6.0.5 on 2026-05-11 07:59

import django.db.models.deletion
import reconciliation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default=reconciliation.models.generate_recon_ref, max_length=20, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_money_reference', models.CharField(blank=True, max_length=100)),
                ('system_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('balanced', 'Balanced'), ('discrepancy', 'Discrepancy Raised'), ('investigating', 'Under Investigation'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('discrepancy_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_collections', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_collections', to='accounts.location')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='OutletReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default=reconciliation.models.generate_recon_ref, max_length=20, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales_system', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_deposit_ref', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted to Back Office'), ('reviewed', 'Reviewed'), ('discrepancy', 'Discrepancy'), ('closed', 'Closed')], default='open', max_length=20)),
                ('discrepancy_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_collections', models.ManyToManyField(blank=True, to='reconciliation.agentcollection')),
                ('backoffice_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_recons_reviewed', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_reconciliations', to='accounts.location')),
                ('outlet_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_recons_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackOfficeReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default=reconciliation.models.generate_recon_ref, max_length=20, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_from_outlets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_confirmed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted to Accounts'), ('reviewed', 'Under Review'), ('signed_off', 'Signed Off')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_signoffs', to=settings.AUTH_USER_MODEL)),
                ('backoffice_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backoffice_recons', to=settings.AUTH_USER_MODEL)),
                ('outlet_reconciliations', models.ManyToManyField(blank=True, to='reconciliation.outletreconciliation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
