# Generated by Django 5.2.8 on 2026-05-12 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subsidy'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='subsidy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='products.subsidy'),
        ),
        migrations.AddField(
            model_name='sale',
            name='subsidy_discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual discount amount deducted at time of sale', max_digits=12),
        ),
    ]
