# Generated by Django 5.2.8 on 2026-05-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0002_sale_subsidy_sale_subsidy_discount_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registered_at',
            field=models.ForeignKey(blank=True, help_text='Outlet where this customer was first registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.location'),
        ),
    ]
