# Generated by Django 5.2.8 on 2026-05-12 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Amount in currency if fixed, or % value if percentage', max_digits=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('funder', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidies_created', to=settings.AUTH_USER_MODEL)),
                ('outlets', models.ManyToManyField(blank=True, help_text='Outlets where this subsidy is available', limit_choices_to={'location_type': 'outlet'}, related_name='subsidies', to='accounts.location')),
                ('products', models.ManyToManyField(blank=True, help_text='Products this subsidy can be applied to', related_name='subsidies', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Subsidies',
                'ordering': ['-created_at'],
            },
        ),
    ]
