# Generated by Django 5.2.8 on 2026-05-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subsidy'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='combos',
            field=models.ManyToManyField(blank=True, help_text='Combos this subsidy can be applied to', related_name='subsidies', to='products.combo'),
        ),
    ]
